CREATE TABLE 'clan_battle_recommend_data' ('level_id' INTEGER NOT NULL, 'recommend_group' INTEGER NOT NULL, 'level_from' INTEGER NOT NULL, 'level_to' INTEGER NOT NULL, 'atack_party_count' INTEGER NOT NULL, 'magic_party_count' INTEGER NOT NULL, PRIMARY KEY('level_id'));
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/1, /*recommend_group*/1, /*level_from*/10, /*level_to*/45, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/2, /*recommend_group*/1, /*level_from*/46, /*level_to*/65, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/3, /*recommend_group*/1, /*level_from*/66, /*level_to*/85, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/4, /*recommend_group*/2, /*level_from*/86, /*level_to*/105, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/5, /*recommend_group*/2, /*level_from*/106, /*level_to*/125, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/6, /*recommend_group*/2, /*level_from*/126, /*level_to*/145, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/7, /*recommend_group*/3, /*level_from*/146, /*level_to*/165, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/8, /*recommend_group*/3, /*level_from*/166, /*level_to*/185, /*atack_party_count*/2, /*magic_party_count*/2);
INSERT INTO `clan_battle_recommend_data` VALUES (/*level_id*/9, /*recommend_group*/3, /*level_from*/186, /*level_to*/205, /*atack_party_count*/2, /*magic_party_count*/2);
CREATE INDEX 'clan_battle_recommend_data_0_recommend_group' on 'clan_battle_recommend_data'('recommend_group');
