CREATE TABLE 'pkb_pitcher_ball_type' ('pitcher_id' INTEGER NOT NULL, 'ball_type' INTEGER NOT NULL, 'ball_type_name' TEXT NOT NULL, PRIMARY KEY('pitcher_id','ball_type'));
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/1, /*ball_type*/1, /*ball_type_name*/"直球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/1, /*ball_type*/2, /*ball_type_name*/"曲球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/2, /*ball_type*/3, /*ball_type_name*/"直球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/2, /*ball_type*/4, /*ball_type_name*/"伸卡球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/2, /*ball_type*/6, /*ball_type_name*/"S曲球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/7, /*ball_type_name*/"直球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/8, /*ball_type_name*/"曲球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/9, /*ball_type_name*/"滑球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/5, /*ball_type_name*/"伸卡球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/16, /*ball_type_name*/"噴射球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/10, /*ball_type_name*/"初音☆幻覺球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/3, /*ball_type*/11, /*ball_type_name*/"初音☆消失球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/4, /*ball_type*/12, /*ball_type_name*/"直球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/4, /*ball_type*/13, /*ball_type_name*/"曲球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/4, /*ball_type*/14, /*ball_type_name*/"伸卡球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/4, /*ball_type*/17, /*ball_type_name*/"昇龍終結球");
INSERT INTO `pkb_pitcher_ball_type` VALUES (/*pitcher_id*/4, /*ball_type*/18, /*ball_type_name*/"昇龍擺尾球");
CREATE INDEX 'pkb_pitcher_ball_type_0_pitcher_id' on 'pkb_pitcher_ball_type'('pitcher_id');
